language: clojure

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - lein spec spec -f d
  - lein cucumber --plugin pretty
jdk:
  - oraclejdk8
