language: clojure

node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - lein test
  - lein run&
  - lein test :acceptance
  - lein doo phantom test once
  - lein doo node node-test once
jdk:
  - oraclejdk8
